### ISSUE TITLE
FontAwesome not found

### ISSUE THREAD

**Issue by chilts** [maximevaillancourt/json-feed-viewer#2]
In the console/network tab, it shows that a link to FontAwesome is a 404. I think it's `https://json-feed-viewer.herokuapp.com/css/font-awesome-4.7.0.min.css` trying to load it up.

```
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: https://json-feed-viewer.herokuapp.com/fonts/fontawesome-webfont.woff?v=4.7.0
```

* https://json-feed-viewer.herokuapp.com/fonts/fontawesome-webfont.ttf?v=4.7.0

**Comment by maximevaillancourt** [comment]
Thanks for the bug report! 8dfc71d1f0b8f47fcc69e6d1c98c65a6cc88bb5a fixes this.

**Comment by chilts** [comment]
Yay, I love CDNs. :)
